apiVersion: v1
kind: Secret
metadata:
  name: cv-secrets
stringData:
  SECRET_KEY: "${SECRET_KEY}"
  SENTRY_DSN: "${SENTRY_DSN}"

  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

  MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}" 
  MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}" 

  REDIS_PASSWORD: "${REDIS_PASSWORD}"

  SMTP_USER: "${SMTP_USER}" 
  SMTP_PASSWORD: "${SMTP_PASSWORD}" 
