// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise"
import { OpenAPI } from "./core/OpenAPI"
import { request as __request } from "./core/request"
import type {
  LoginLoginAccessTokenData,
  LoginLoginAccessTokenResponse,
  LoginRecoverPasswordData,
  LoginRecoverPasswordHtmlContentData,
  LoginRecoverPasswordHtmlContentResponse,
  LoginRecoverPasswordResponse,
  LoginResetPasswordData,
  LoginResetPasswordResponse,
  LoginTestTokenResponse,
  PrivateCreateUserData,
  PrivateCreateUserResponse,
  UsersActivateUserData,
  UsersActivateUserResponse,
  UsersCreateUserData,
  UsersCreateUserResponse,
  UsersDeactivateUserData,
  UsersDeactivateUserResponse,
  UsersDeleteUserData,
  UsersDeleteUserMeResponse,
  UsersDeleteUserResponse,
  UsersReadUserByIdData,
  UsersReadUserByIdResponse,
  UsersReadUserMeResponse,
  UsersReadUsersByRoleData,
  UsersReadUsersByRoleResponse,
  UsersReadUsersData,
  UsersReadUsersResponse,
  UsersRegisterUserData,
  UsersRegisterUserResponse,
  UsersSearchUsersData,
  UsersSearchUsersResponse,
  UsersUpdatePasswordMeData,
  UsersUpdatePasswordMeResponse,
  UsersUpdateUserData,
  UsersUpdateUserMeData,
  UsersUpdateUserMeResponse,
  UsersUpdateUserResponse,
  UsersUpdateUserRoleData,
  UsersUpdateUserRoleResponse,
  UtilsClearCacheResponse,
  UtilsGetDocsAccessInfoResponse,
  UtilsGetExampleWithDynamicSettingResponse,
  UtilsGetInternalErrorResponse,
  UtilsGetRolesResponse,
  UtilsHealthCheckResponse,
  UtilsReadEnumsResponse,
  UtilsReadRootResponse,
  UtilsTestEmailData,
  UtilsTestEmailResponse,
} from "./types.gen"

export class LoginService {
  /**
   * Login Access Token
   * ## Login de usuario con email y contraseña
   *
   * Endpoint compatible con OAuth2 para obtener un token de acceso JWT.
   *
   * ### Parámetros
   * - **email**: Email del usuario registrado
   * - **password**: Contraseña del usuario
   *
   * ### Retorna
   * - **access_token**: Token JWT para autenticación en futuras peticiones
   * - **token_type**: Tipo de token (siempre "bearer")
   *
   * ### Errores
   * - **400**: Email o contraseña incorrectos
   * - **400**: Usuario inactivo
   *
   * ### Ejemplo de uso
   * ```python
   * # Request
   * POST /api/v1/login/access-token/
   * {
   * "email": "user@example.com",
   * "password": "secretpassword"
   * }
   *
   * # Response
   * {
   * "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
   * "token_type": "bearer"
   * }
   * ```
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Token Successful Response
   * @throws ApiError
   */
  public static loginAccessToken(
    data: LoginLoginAccessTokenData,
  ): CancelablePromise<LoginLoginAccessTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/login/access-token",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Test Token
   * ## Verificar validez del token de acceso
   *
   * Endpoint para probar si el token JWT actual es válido y obtener
   * información del usuario autenticado.
   *
   * ### Autenticación
   * Requiere header de autorización: `Authorization: Bearer <token>`
   *
   * ### Retorna
   * Información pública del usuario autenticado
   *
   * ### Errores
   * - **401**: Token inválido, expirado o no proporcionado
   * - **403**: Usuario inactivo
   *
   * ### Ejemplo de uso
   * ```python
   * # Request
   * POST /api/v1/login/test-token/
   * Headers: {
   * "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
   * }
   *
   * # Response
   * {
   * "id": "123e4567-e89b-12d3-a456-426614174000",
   * "email": "user@example.com",
   * "full_name": "John Doe",
   * "is_active": true,
   * "is_superuser": false,
   * "role": "viewer"
   * }
   * ```
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static testToken(): CancelablePromise<LoginTestTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/login/test-token",
    })
  }

  /**
   * Recover Password
   * ## Solicitar recuperación de contraseña
   *
   * Envía un email con un token de recuperación de contraseña al usuario.
   *
   * ### Parámetros
   * - **email**: Email del usuario que solicita recuperar su contraseña
   *
   * ### Retorna
   * Mensaje de confirmación indicando que se envió el email
   *
   * ### Errores
   * - **404**: No existe un usuario con ese email
   *
   * ### Notas
   * - El token de recuperación tiene una validez limitada (configurada en settings)
   * - El email contiene un enlace para restablecer la contraseña
   * - Por seguridad, siempre devuelve 200 incluso si el email no existe (en producción)
   *
   * ### Ejemplo de uso
   * ```python
   * # Request
   * POST /api/v1/password-recovery/user@example.com/
   *
   * # Response
   * {
   * "message": "Password recovery email sent"
   * }
   * ```
   * @param data The data for the request.
   * @param data.email
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static recoverPassword(
    data: LoginRecoverPasswordData,
  ): CancelablePromise<LoginRecoverPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/password-recovery/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Reset Password
   * ## Restablecer contraseña con token
   *
   * Permite al usuario establecer una nueva contraseña usando el token
   * recibido por email en el proceso de recuperación.
   *
   * ### Parámetros
   * - **token**: Token de recuperación recibido por email
   * - **new_password**: Nueva contraseña que se desea establecer
   *
   * ### Retorna
   * Mensaje de confirmación de actualización exitosa
   *
   * ### Errores
   * - **400**: Token inválido o expirado
   * - **404**: Usuario no encontrado
   * - **400**: Usuario inactivo
   *
   * ### Flujo completo
   * 1. Usuario solicita recuperación en `/password-recovery/{email}/`
   * 2. Usuario recibe email con token
   * 3. Usuario envía token + nueva contraseña a este endpoint
   * 4. Contraseña se actualiza y puede hacer login
   *
   * ### Ejemplo de uso
   * ```python
   * # Request
   * POST /api/v1/reset-password/
   * {
   * "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
   * "new_password": "newSecurePassword123!"
   * }
   *
   * # Response
   * {
   * "message": "Password updated successfully"
   * }
   * ```
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static resetPassword(
    data: LoginResetPasswordData,
  ): CancelablePromise<LoginResetPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/reset-password",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Recover Password Html Content
   * ## Obtener contenido HTML del email de recuperación (Solo Superusuarios)
   *
   * Endpoint de utilidad para previsualizar el contenido del email de
   * recuperación de contraseña. Solo accesible por superusuarios.
   *
   * ### Autenticación
   * Requiere ser superusuario activo
   *
   * ### Parámetros
   * - **email**: Email del usuario para generar el email de prueba
   *
   * ### Retorna
   * HTML del email que se enviaría al usuario
   *
   * ### Errores
   * - **401**: No autenticado
   * - **403**: No es superusuario
   * - **404**: Usuario no encontrado
   *
   * ### Uso
   * Este endpoint es principalmente para:
   * - Probar el diseño del email de recuperación
   * - Verificar que los templates funcionan correctamente
   * - Debugging en desarrollo
   *
   * ### Ejemplo de uso
   * ```python
   * # Request
   * POST /api/v1/password-recovery-html-content/user@example.com/
   * Headers: {
   * "Authorization": "Bearer <superuser_token>"
   * }
   *
   * # Response
   * HTML completo del email con el token de recuperación
   * ```
   * @param data The data for the request.
   * @param data.email
   * @returns string Successful Response
   * @throws ApiError
   */
  public static recoverPasswordHtmlContent(
    data: LoginRecoverPasswordHtmlContentData,
  ): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/password-recovery-html-content/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class PrivateService {
  /**
   * Create User
   * Create a new user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static createUser(
    data: PrivateCreateUserData,
  ): CancelablePromise<PrivateCreateUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/private/users",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class UsersService {
  /**
   * Read Users
   * Lista todos los usuarios (solo administradores y desarrolladores).
   *
   * Requiere autenticación y rol de ADMIN o DEVELOPER.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns UserListResponse Successful Response
   * @throws ApiError
   */
  public static readUsers(
    data: UsersReadUsersData = {},
  ): CancelablePromise<UsersReadUsersResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create User
   * Crea un nuevo usuario (diseñadores de modelos, editores de modelos, configuradores, espectadores, críticos, administradores o desarrollador).
   *
   * **Permisos requeridos:**
   * - Administradores pueden crear: diseñadores de modelos, editores de modelos, configuradores, espectadores, críticos  y administradores
   * - Desarrolladores pueden crear: todos los roles, incluido desarrollador
   *
   * **Validaciones**:
   * - Email único
   * - Contraseña fuerte (mínimo 8 caracteres)
   * - Rol válido
   * - Solo desarrolladores pueden crear otros desarrolladores
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static createUser(
    data: UsersCreateUserData,
  ): CancelablePromise<UsersCreateUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Users By Role
   * @param data The data for the request.
   * @param data.role
   * @param data.skip
   * @param data.limit
   * @returns UserListResponse Successful Response
   * @throws ApiError
   */
  public static readUsersByRole(
    data: UsersReadUsersByRoleData,
  ): CancelablePromise<UsersReadUsersByRoleResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/by-role/{role}",
      path: {
        role: data.role,
      },
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read User Me
   * Get current user.
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/me",
    })
  }

  /**
   * Delete User Me
   * Delete own user (async).
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/me",
    })
  }

  /**
   * Update User Me
   * Update own user (async).
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static updateUserMe(
    data: UsersUpdateUserMeData,
  ): CancelablePromise<UsersUpdateUserMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/me",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Password Me
   * Update own password (async).
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static updatePasswordMe(
    data: UsersUpdatePasswordMeData,
  ): CancelablePromise<UsersUpdatePasswordMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/me/password",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Register User
   * Create new user without the need to be logged in (async).
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static registerUser(
    data: UsersRegisterUserData,
  ): CancelablePromise<UsersRegisterUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/signup",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read User By Id
   * Get a specific user by id (async).
   * @param data The data for the request.
   * @param data.userId
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static readUserById(
    data: UsersReadUserByIdData,
  ): CancelablePromise<UsersReadUserByIdResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update User
   * Update a user (async).
   * @param data The data for the request.
   * @param data.userId
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static updateUser(
    data: UsersUpdateUserData,
  ): CancelablePromise<UsersUpdateUserResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete User
   * Delete a user (async).
   * @param data The data for the request.
   * @param data.userId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUser(
    data: UsersDeleteUserData,
  ): CancelablePromise<UsersDeleteUserResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update User Role
   * Update a user's role (async).
   * @param data The data for the request.
   * @param data.userId
   * @param data.role
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static updateUserRole(
    data: UsersUpdateUserRoleData,
  ): CancelablePromise<UsersUpdateUserRoleResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/users/{user_id}/role",
      path: {
        user_id: data.userId,
      },
      query: {
        role: data.role,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Search Users
   * Search users by email or name (async).
   * @param data The data for the request.
   * @param data.searchTerm
   * @param data.skip
   * @param data.limit
   * @returns UserListResponse Successful Response
   * @throws ApiError
   */
  public static searchUsers(
    data: UsersSearchUsersData,
  ): CancelablePromise<UsersSearchUsersResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/search/{search_term}",
      path: {
        search_term: data.searchTerm,
      },
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Activate User
   * Activate a user (async).
   * @param data The data for the request.
   * @param data.userId
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static activateUser(
    data: UsersActivateUserData,
  ): CancelablePromise<UsersActivateUserResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/{user_id}/activate",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Deactivate User
   * Deactivate a user (async).
   * @param data The data for the request.
   * @param data.userId
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static deactivateUser(
    data: UsersDeactivateUserData,
  ): CancelablePromise<UsersDeactivateUserResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/{user_id}/deactivate",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class UtilsService {
  /**
   * Read Root
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static readRoot(): CancelablePromise<UtilsReadRootResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/utils",
    })
  }

  /**
   * Health Check
   * @returns boolean Successful Response
   * @throws ApiError
   */
  public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/utils/health-check",
    })
  }

  /**
   * Get Docs Access Info
   * Endpoint de ayuda para acceder a la documentación interna.
   *
   * Proporciona información sobre cómo obtener acceso a /internal-docs/
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getDocsAccessInfo(): CancelablePromise<UtilsGetDocsAccessInfoResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/utils/docs-access",
    })
  }

  /**
   * Get Internal Error
   * Este endpoint simula un error inesperado.
   * Será capturado por el `generic_exception_handler`.
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getInternalError(): CancelablePromise<UtilsGetInternalErrorResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/utils/test/internal-error",
    })
  }

  /**
   * Test Email
   * Test emails.
   * @param data The data for the request.
   * @param data.emailTo
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static testEmail(
    data: UtilsTestEmailData,
  ): CancelablePromise<UtilsTestEmailResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/utils/test-email",
      query: {
        email_to: data.emailTo,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Example With Dynamic Setting
   * Endpoint para probar el servicio de variables dinámicas configurables.
   * Usamos el servicio para obtener un ajuste dinámico
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getExampleWithDynamicSetting(): CancelablePromise<UtilsGetExampleWithDynamicSettingResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/utils/test/setting",
    })
  }

  /**
   * Get Roles
   * Retrieve the roles of the system.
   * @returns string Successful Response
   * @throws ApiError
   */
  public static getRoles(): CancelablePromise<UtilsGetRolesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/utils/roles",
    })
  }

  /**
   * Obtener todas las opciones (enums) para los selectores del frontend
   * Proporciona una lista consolidada de todos los valores de enumeración
   * utilizados en la aplicación.
   *
   * Esto es útil para poblar dinámicamente los menús desplegables,
   * filtros y otros componentes en el frontend sin tener que codificar
   * estos valores.
   * @returns AllEnumsResponse Successful Response
   * @throws ApiError
   */
  public static readEnums(): CancelablePromise<UtilsReadEnumsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/utils/options",
    })
  }

  /**
   * Clear Cache
   * Limpia toda la caché de la aplicación.
   *
   * Elimina todas las claves de Redis que empiezan con 'fastapi-cache:'
   * (usadas por el decorador @cache) sin afectar otros datos en Redis.
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static clearCache(): CancelablePromise<UtilsClearCacheResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/utils/clear-cache",
    })
  }
}
