// This file is auto-generated by @hey-api/openapi-ts

/**
 * Modelo de respuesta que contiene todas las listas de enums.
 */
export type AllEnumsResponse = {
  userRoles: Array<EnumValue>
  productCategories: Array<EnumValue>
  orderStatuses: Array<EnumValue>
  pizzaBakingOptions: Array<EnumValue>
  genericSizes: Array<EnumValue>
}

/**
 * Modelo para representar un par valor/etiqueta de un enum.
 */
export type EnumValue = {
  value: string
  label: string
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type LoginRequest = {
  email: string
  password: string
}

export type Message = {
  message: string
}

export type NewPassword = {
  token: string
  new_password: string
}

export type PrivateUserCreate = {
  email: string
  password: string
  is_verified?: boolean
}

export type Token = {
  access_token: string
  token_type?: string
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type UserCreate = {
  email: string
  is_superuser?: boolean
  role?: UserRole
  password: string
}

/**
 * Respuesta para listar los usuarios.
 */
export type UserListResponse = {
  data: Array<UserPublic>
  count: number
  page: number
  size: number
  total_pages: number
  has_next: boolean
  has_prev: boolean
}

export type UserPublic = {
  email: string
  is_superuser?: boolean
  role?: UserRole
  id: string
}

export type UserRegister = {
  email: string
  password: string
}

/**
 * Enums para definir los roles del usuario
 */
export type UserRole = "developer" | "admin" | "user"

export type UserUpdate = {
  email?: string | null
  is_superuser?: boolean
  role?: UserRole
  password?: string | null
}

export type UserUpdateMe = {
  email?: string | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type LoginLoginAccessTokenData = {
  requestBody: LoginRequest
}

export type LoginLoginAccessTokenResponse = Token

export type LoginTestTokenResponse = UserPublic

export type LoginRecoverPasswordData = {
  email: string
}

export type LoginRecoverPasswordResponse = Message

export type LoginResetPasswordData = {
  requestBody: NewPassword
}

export type LoginResetPasswordResponse = Message

export type LoginRecoverPasswordHtmlContentData = {
  email: string
}

export type LoginRecoverPasswordHtmlContentResponse = string

export type PrivateCreateUserData = {
  requestBody: PrivateUserCreate
}

export type PrivateCreateUserResponse = UserPublic

export type UsersReadUsersData = {
  limit?: number
  skip?: number
}

export type UsersReadUsersResponse = UserListResponse

export type UsersCreateUserData = {
  requestBody: UserCreate
}

export type UsersCreateUserResponse = UserPublic

export type UsersReadUsersByRoleData = {
  limit?: number
  role: UserRole
  skip?: number
}

export type UsersReadUsersByRoleResponse = UserListResponse

export type UsersReadUserMeResponse = UserPublic

export type UsersDeleteUserMeResponse = Message

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe
}

export type UsersUpdateUserMeResponse = UserPublic

export type UsersUpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type UsersUpdatePasswordMeResponse = Message

export type UsersRegisterUserData = {
  requestBody: UserRegister
}

export type UsersRegisterUserResponse = UserPublic

export type UsersReadUserByIdData = {
  userId: string
}

export type UsersReadUserByIdResponse = UserPublic

export type UsersUpdateUserData = {
  requestBody: UserUpdate
  userId: string
}

export type UsersUpdateUserResponse = UserPublic

export type UsersDeleteUserData = {
  userId: string
}

export type UsersDeleteUserResponse = Message

export type UsersUpdateUserRoleData = {
  role: UserRole
  userId: string
}

export type UsersUpdateUserRoleResponse = UserPublic

export type UsersSearchUsersData = {
  limit?: number
  searchTerm: string
  skip?: number
}

export type UsersSearchUsersResponse = UserListResponse

export type UsersActivateUserData = {
  userId: string
}

export type UsersActivateUserResponse = UserPublic

export type UsersDeactivateUserData = {
  userId: string
}

export type UsersDeactivateUserResponse = UserPublic

export type UtilsReadRootResponse = unknown

export type UtilsHealthCheckResponse = boolean

export type UtilsGetDocsAccessInfoResponse = unknown

export type UtilsGetInternalErrorResponse = unknown

export type UtilsTestEmailData = {
  emailTo: string
}

export type UtilsTestEmailResponse = Message

export type UtilsGetExampleWithDynamicSettingResponse = unknown

export type UtilsGetRolesResponse = Array<string>

export type UtilsReadEnumsResponse = AllEnumsResponse

export type UtilsClearCacheResponse = unknown
